version: '2'
services:
  v2ray:
    image: teddysun/v2ray
    container_name: ref.v2ray
    hostname: ref.v2ray
    networks:
      ref.net:
        ipv4_address: 172.20.128.12
    ports:
      - 8888:8888
      - 8889:8889
    command: [ "/usr/bin/v2ray", "-config", "/root/.config/v2ray/config.json" ]
    extends:
      file: common.yaml
      service: common

  workspace:
    build: ./Dockerfile.workspace
    image: ref.workspace
    container_name: ref.workspace
    hostname: ref.workspace
    networks:
      ref.net:
        ipv4_address: 172.20.128.11
    ports:
      - 25601:25601
    extends:
      file: common.yaml
      service: common
    environment:
      - HTTPS_PROXY=172.20.128.12:8889
      - HTTP_PROXY=172.20.128.12:8889
      - all_proxy=socks5://172.20.128.12:8888


      
networks:
  ref.net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.128.0/24
          gateway: 172.20.128.254

