version: '2'

services:
  ref-workspace:
    build: ./Dockerfile.workspace
    image: ref.workspace2
    container_name: ref.workspace2
    hostname: ref.workspace2
    networks:
      ref.net:
        ipv4_address: 172.20.128.1
    ports:
      - 25601:25601
    extends:
      file: common.yaml
      service: common

networks:
  ref.net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.128.0/24
          gateway: 172.20.128.254

