

x-common-configuration: &common-configuration
  restart: always
  privileged: true
  stdin_open: true
  tty: true
  extra_hosts:
    - "docker-registry:10.186.18.20"
  cap_add:
    - ALL
  security_opt:
    - seccomp:unconfined
  working_dir: /shared
  volumes:
    - /shared:/shared
    - ~/.config:/root/.config

x-proxy-environment: &proxy-environment
  https_proxy: http://172.20.128.12:7890
  http_proxy: http://172.20.128.12:7890
  all_proxy: socks5://172.20.128.12:7890

services:
  clash:
    <<: *common-configuration
    image: dreamacro/clash
    container_name: ref.clash
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    networks:
      ref.net:
        ipv4_address: 172.20.128.12

  workspace:
    <<: *common-configuration
    image: ref.workspace:v2
    build: ./Dockerfile.workspace
    container_name: ref.workspace
    hostname: ref.workspace
    networks:
      ref.net:
        ipv4_address: 172.20.128.11
    ports:
      - "25601:25601"
    environment:
      <<: *proxy-environment
    env_file:
      - env/profile.env

  dropbox:
    <<: *common-configuration
    image: otherguy/dropbox
    container_name: ref.dropbox
    hostname: ref.dropbox
    networks:
      ref.net:
        ipv4_address: 172.20.128.13
    volumes:
      - ~/.config/dropbox:/opt/dropbox/.dropbox
      - /shared/Dropbox:/opt/dropbox/Dropbox
    environment:
      <<: *proxy-environment
      DROPBOX_UID: 0
      DROPBOX_GID: 0

networks:
  ref.net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.128.0/24
          gateway: 172.20.128.254
