version: '2'

services:
  workspace:
    build: ./Dockerfile.workspace
    image: ref.workspace2
    container_name: ref.workspace2
    hostname: ref.workspace2
    networks:
      ref.net:
        ipv4_address: 172.20.128.1
    ports:
      - 25601:25601
    extends:
      file: common.yaml
      service: common

  confluence-postgres:
    build: ./Dockerfile.workspace
    image: blacklabelops/postgres
    container_name: ref.postgres
    hostname: ref.postgres
    networks:
      ref.net:
        ipv4_address: 172.20.128.2
    ports:
      - 25602:25602
    extends:
      file: common.yaml
      service: common
    env_file:
      - env/postgres.env


networks:
  ref.net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.128.0/24
          gateway: 172.20.128.254

