version: '2'
services:
  v2ray:
    image: ref0/v2fly:v1
    container_name: ref.v2ray
    hostname: ref.v2ray
    command: "${V2RAY_SUBSCR_URL}"
    ports:
      # socks
      - "8888:8888"
      # http
      - "8889:8889"
    networks:
      ref.net:
        ipv4_address: 172.20.128.12
    extends:
      file: common.yaml
      service: common

  workspace:
    build: ./Dockerfile.workspace
    image: ref.workspace
    container_name: ref.workspace
    hostname: ref.workspace
    networks:
      ref.net:
        ipv4_address: 172.20.128.11
    ports:
      - 25601:25601
    extends:
      file: common.yaml
      service: common
    environment:
      - https_proxy=172.20.128.12:8889
      - http_proxy=172.20.128.12:8889
      - all_proxy=socks5://172.20.128.12:8888

  dropbox:
    image: otherguy/dropbox
    container_name: ref.dropbox
    hostname: ref.dropbox
    networks:
      ref.net:
        ipv4_address: 172.20.128.13
    volumes:
      - ~/.config/dropbox:/opt/dropbox/.dropbox
      - /shared/Dropbox:/opt/dropbox/Dropbox
    extends:
      file: common.yaml
      service: common
    environment:
      - all_proxy=socks5://172.20.128.12:8888    
      - https_proxy=172.20.128.12:8889
      - http_proxy=172.20.128.12:8889 
      - DROPBOX_UID=0
      - DROPBOX_GID=0



      
networks:
  ref.net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.128.0/24
          gateway: 172.20.128.254

